// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      includereplace: {
        dist: {
          options: {
            prefix: '@@',
            suffix: ''
          },
          src: 'src/*.html',
          dest: 'production/'
        }
      },
      clean: {
        files: ["production/_*.html", "production/*.js"]
      },
      copy: {
        main: {
          files: [
            {
              expand: true,
              cwd: "src/img/",
              src: ["**"],
              dest: "production/img"
            }, {
              expand: true,
              cwd: "src/fonts/",
              src: ["**"],
              dest: "production/fonts"
            }, {
              expand: true,
              cwd: "src/js",
              src: ["**"],
              dest: "production/js"
            }, {
              expand: true,
              cwd: "src/img/svg/",
              src: "*",
              dest: "production/img/svg/",
              filter: "isFile"
            }
          ]
        }
      },
      watch: {
        files: ["src/*.html", "src/js/*.js", "src/img/icons*.png"],
        tasks: ["includereplace", "copy", "clean"]
      }
    });
    require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);
    grunt.registerTask("default", ["watch"]);
    return grunt.registerTask("a", ["clean", "includereplace", "copy"]);
  };

}).call(this);
